# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_gamewrap', [dirname(__file__)])
        except ImportError:
            import _gamewrap
            return _gamewrap
        if fp is not None:
            try:
                _mod = imp.load_module('_gamewrap', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _gamewrap = swig_import_helper()
    del swig_import_helper
else:
    import _gamewrap
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class pong(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, pong, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, pong, name)
    __repr__ = _swig_repr
    def grabScreen(self, *args): return _gamewrap.pong_grabScreen(self, *args)
    def getTerminal(self): return _gamewrap.pong_getTerminal(self)
    def getReward(self): return _gamewrap.pong_getReward(self)
    def clearScreen(self): return _gamewrap.pong_clearScreen(self)
    def play(self, *args): return _gamewrap.pong_play(self, *args)
    def __init__(self): 
        this = _gamewrap.new_pong()
        try: self.this.append(this)
        except: self.this = this
    def newGame(self): return _gamewrap.pong_newGame(self)
    def getScreen(self): return _gamewrap.pong_getScreen(self)
    __swig_destroy__ = _gamewrap.delete_pong
    __del__ = lambda self : None;
pong_swigregister = _gamewrap.pong_swigregister
pong_swigregister(pong)

# This file is compatible with both classic and new-style classes.


